# Generated by Django 5.0.4 on 2024-04-28 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='myBlog_post', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
